baseURL = "https://noematic.eu/"
languageCode = "fr-fr"
theme = "noematic"

# navigation
[menu]

  #[[menu.header]]
  #name = "About"
  #URL = "#about"
  #weight = 2


  #[[menu.footer]]
  #name = "About"
  #URL = "#about"
  #weight = 2


[params]

  sections = ["showcase"]

  [params.logo]
    text1 = "Noematic"

  [params.footer]
      copyright = "2020 Â© Noematic. All rights reserved."